// Generated by IB v0.4.3 gem. Do not edit it manually
// Run `rake ib:open` to refresh

#import <UIKit/UIKit.h>
#import <Foundation/Foundation.h>
#import <CoreGraphics/CoreGraphics.h>

@interface AppDelegate: UIResponder <UIApplicationDelegate>
@end

@interface DetailController: UIImageIViewController

@property IBOutlet UIBarButtonItem * button;

@end

